// Mocks generated by Mockito 5.4.6 from annotations
// in finance_manager_2026/test/features/transactions/presentation/add_transaction_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:finance_manager_2026/features/accounts/application/account_service.dart'
    as _i7;
import 'package:finance_manager_2026/features/accounts/domain/account_models.dart'
    as _i3;
import 'package:finance_manager_2026/features/transactions/application/transaction_service.dart'
    as _i4;
import 'package:finance_manager_2026/features/transactions/domain/transaction_model.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:riverpod_annotation/riverpod_annotation.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAutoDisposeProviderRef_0<State> extends _i1.SmartFake
    implements _i2.AutoDisposeProviderRef<State> {
  _FakeAutoDisposeProviderRef_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVirtualAccount_1 extends _i1.SmartFake
    implements _i3.VirtualAccount {
  _FakeVirtualAccount_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TransactionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionService extends _i1.Mock
    implements _i4.TransactionService {
  MockTransactionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AutoDisposeProviderRef<_i4.TransactionService> get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _FakeAutoDisposeProviderRef_0<_i4.TransactionService>(
              this,
              Invocation.getter(#ref),
            ),
          )
          as _i2.AutoDisposeProviderRef<_i4.TransactionService>);

  @override
  _i5.Future<void> addTransaction({
    required double? amount,
    required _i6.TransactionType? type,
    required String? label,
    required DateTime? date,
    required _i3.RealAccount? realAccount,
    required _i3.VirtualAccount? targetVirtualAccount,
    _i6.TransactionStep? step = _i6.TransactionStep.completed,
    String? category,
    String? note,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addTransaction, [], {
              #amount: amount,
              #type: type,
              #label: label,
              #date: date,
              #realAccount: realAccount,
              #targetVirtualAccount: targetVirtualAccount,
              #step: step,
              #category: category,
              #note: note,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addSplitTransaction({
    required double? totalAmount,
    required _i6.TransactionType? type,
    required String? label,
    required DateTime? date,
    required _i3.RealAccount? realAccount,
    required List<({_i3.VirtualAccount account, double amount})>? splits,
    _i6.TransactionStep? step = _i6.TransactionStep.completed,
    String? category,
    String? note,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addSplitTransaction, [], {
              #totalAmount: totalAmount,
              #type: type,
              #label: label,
              #date: date,
              #realAccount: realAccount,
              #splits: splits,
              #step: step,
              #category: category,
              #note: note,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addAdjustment({
    required double? adjustmentAmount,
    required String? label,
    required _i3.RealAccount? realAccount,
    required _i3.VirtualAccount? targetVirtualAccount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addAdjustment, [], {
              #adjustmentAmount: adjustmentAmount,
              #label: label,
              #realAccount: realAccount,
              #targetVirtualAccount: targetVirtualAccount,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteTransaction(_i6.TransactionModel? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [transaction]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addTransfer({
    required double? amount,
    required String? label,
    required DateTime? date,
    required _i3.VirtualAccount? sourceVirtualAccount,
    required _i3.VirtualAccount? targetVirtualAccount,
    String? category,
    String? note,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addTransfer, [], {
              #amount: amount,
              #label: label,
              #date: date,
              #sourceVirtualAccount: sourceVirtualAccount,
              #targetVirtualAccount: targetVirtualAccount,
              #category: category,
              #note: note,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateTransaction({
    required _i6.TransactionModel? originalTransaction,
    required double? amount,
    required _i6.TransactionType? type,
    required String? label,
    required DateTime? date,
    required _i3.RealAccount? realAccount,
    required _i3.VirtualAccount? targetVirtualAccount,
    _i6.TransactionStep? step,
    String? category,
    String? note,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTransaction, [], {
              #originalTransaction: originalTransaction,
              #amount: amount,
              #type: type,
              #label: label,
              #date: date,
              #realAccount: realAccount,
              #targetVirtualAccount: targetVirtualAccount,
              #step: step,
              #category: category,
              #note: note,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateSplitTransaction({
    required _i6.TransactionModel? originalTransaction,
    required double? totalAmount,
    required _i6.TransactionType? type,
    required String? label,
    required DateTime? date,
    required _i3.RealAccount? realAccount,
    required List<({_i3.VirtualAccount account, double amount})>? splits,
    _i6.TransactionStep? step,
    String? category,
    String? note,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateSplitTransaction, [], {
              #originalTransaction: originalTransaction,
              #totalAmount: totalAmount,
              #type: type,
              #label: label,
              #date: date,
              #realAccount: realAccount,
              #splits: splits,
              #step: step,
              #category: category,
              #note: note,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> confirmTransaction(
    _i6.TransactionModel? originalTransaction,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#confirmTransaction, [originalTransaction]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> cancelTransaction(
    _i6.TransactionModel? originalTransaction,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cancelTransaction, [originalTransaction]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [AccountService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountService extends _i1.Mock implements _i7.AccountService {
  MockAccountService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AutoDisposeProviderRef<_i7.AccountService> get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _FakeAutoDisposeProviderRef_0<_i7.AccountService>(
              this,
              Invocation.getter(#ref),
            ),
          )
          as _i2.AutoDisposeProviderRef<_i7.AccountService>);

  @override
  _i5.Future<void> ensureUserInitialized() =>
      (super.noSuchMethod(
            Invocation.method(#ensureUserInitialized, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> createRealAccount({
    required String? name,
    required String? bankName,
    required double? initialBalance,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createRealAccount, [], {
              #name: name,
              #bankName: bankName,
              #initialBalance: initialBalance,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.VirtualAccount> createVirtualAccount({
    required String? realAccountId,
    required String? name,
    _i3.VirtualAccountType? type = _i3.VirtualAccountType.userBudget,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createVirtualAccount, [], {
              #realAccountId: realAccountId,
              #name: name,
              #type: type,
            }),
            returnValue: _i5.Future<_i3.VirtualAccount>.value(
              _FakeVirtualAccount_1(
                this,
                Invocation.method(#createVirtualAccount, [], {
                  #realAccountId: realAccountId,
                  #name: name,
                  #type: type,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.VirtualAccount>);

  @override
  _i5.Future<void> deleteVirtualAccount(_i3.VirtualAccount? virtualAccount) =>
      (super.noSuchMethod(
            Invocation.method(#deleteVirtualAccount, [virtualAccount]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateRealAccountMetadata({
    required _i3.RealAccount? account,
    String? name,
    String? bankName,
    DateTime? openingDate,
    String? accountNumber,
    String? officialName,
    String? iban,
    String? bic,
    String? swift,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateRealAccountMetadata, [], {
              #account: account,
              #name: name,
              #bankName: bankName,
              #openingDate: openingDate,
              #accountNumber: accountNumber,
              #officialName: officialName,
              #iban: iban,
              #bic: bic,
              #swift: swift,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> renameRealAccount(
    _i3.RealAccount? account,
    String? newName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#renameRealAccount, [account, newName]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> shareRealAccount(_i3.RealAccount? account, String? email) =>
      (super.noSuchMethod(
            Invocation.method(#shareRealAccount, [account, email]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, int>> repairData() =>
      (super.noSuchMethod(
            Invocation.method(#repairData, []),
            returnValue: _i5.Future<Map<String, int>>.value(<String, int>{}),
          )
          as _i5.Future<Map<String, int>>);

  @override
  _i5.Future<void> renameVirtualAccount(
    _i3.VirtualAccount? account,
    String? newName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#renameVirtualAccount, [account, newName]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteRealAccount(_i3.RealAccount? account) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRealAccount, [account]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
