// Mocks generated by Mockito 5.4.6 from annotations
// in finance_manager_2026/test/features/transactions/presentation/projected_balance_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:finance_manager_2026/features/transactions/application/recurring_transaction_service.dart'
    as _i3;
import 'package:finance_manager_2026/features/transactions/domain/recurring_transaction_model.dart'
    as _i5;
import 'package:finance_manager_2026/features/transactions/domain/transaction_model.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:riverpod_annotation/riverpod_annotation.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAutoDisposeProviderRef_0<State> extends _i1.SmartFake
    implements _i2.AutoDisposeProviderRef<State> {
  _FakeAutoDisposeProviderRef_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RecurringTransactionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecurringTransactionService extends _i1.Mock
    implements _i3.RecurringTransactionService {
  MockRecurringTransactionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AutoDisposeProviderRef<_i3.RecurringTransactionService> get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue:
                _FakeAutoDisposeProviderRef_0<_i3.RecurringTransactionService>(
                  this,
                  Invocation.getter(#ref),
                ),
          )
          as _i2.AutoDisposeProviderRef<_i3.RecurringTransactionService>);

  @override
  _i4.Future<void> addRecurringTransaction({
    required _i5.RecurrenceFrequency? frequency,
    int? interval = 1,
    required DateTime? startDate,
    DateTime? endDate,
    required String? realAccountId,
    required double? amount,
    required String? label,
    String? note,
    required _i6.TransactionType? type,
    List<_i6.TransactionSplit>? splits = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addRecurringTransaction, [], {
              #frequency: frequency,
              #interval: interval,
              #startDate: startDate,
              #endDate: endDate,
              #realAccountId: realAccountId,
              #amount: amount,
              #label: label,
              #note: note,
              #type: type,
              #splits: splits,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteRecurringTransaction(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRecurringTransaction, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.TransactionModel>> generateOccurrences(
    DateTime? untilDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generateOccurrences, [untilDate]),
            returnValue: _i4.Future<List<_i6.TransactionModel>>.value(
              <_i6.TransactionModel>[],
            ),
          )
          as _i4.Future<List<_i6.TransactionModel>>);
}
