// Mocks generated by Mockito 5.4.6 from annotations
// in finance_manager_2026/test/features/transactions/presentation/upcoming_transactions_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:finance_manager_2026/features/accounts/domain/account_models.dart'
    as _i6;
import 'package:finance_manager_2026/features/transactions/application/transaction_service.dart'
    as _i3;
import 'package:finance_manager_2026/features/transactions/domain/transaction_model.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:riverpod_annotation/riverpod_annotation.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAutoDisposeProviderRef_0<State> extends _i1.SmartFake
    implements _i2.AutoDisposeProviderRef<State> {
  _FakeAutoDisposeProviderRef_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TransactionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionService extends _i1.Mock
    implements _i3.TransactionService {
  MockTransactionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AutoDisposeProviderRef<_i3.TransactionService> get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _FakeAutoDisposeProviderRef_0<_i3.TransactionService>(
              this,
              Invocation.getter(#ref),
            ),
          )
          as _i2.AutoDisposeProviderRef<_i3.TransactionService>);

  @override
  _i4.Future<void> addTransaction({
    required double? amount,
    required _i5.TransactionType? type,
    required String? label,
    required DateTime? date,
    required _i6.RealAccount? realAccount,
    required _i6.VirtualAccount? targetVirtualAccount,
    String? category,
    String? note,
    _i5.TransactionStep? step = _i5.TransactionStep.completed,
    _i5.TransactionStatus? status = _i5.TransactionStatus.none,
    String? recurringTransactionId,
    String? externalEntityId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addTransaction, [], {
              #amount: amount,
              #type: type,
              #label: label,
              #date: date,
              #realAccount: realAccount,
              #targetVirtualAccount: targetVirtualAccount,
              #category: category,
              #note: note,
              #step: step,
              #status: status,
              #recurringTransactionId: recurringTransactionId,
              #externalEntityId: externalEntityId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addSplitTransaction({
    required double? totalAmount,
    required _i5.TransactionType? type,
    required String? label,
    required DateTime? date,
    required _i6.RealAccount? realAccount,
    required List<({_i6.VirtualAccount account, double amount})>? splits,
    String? category,
    String? note,
    _i5.TransactionStep? step = _i5.TransactionStep.completed,
    _i5.TransactionStatus? status = _i5.TransactionStatus.none,
    String? recurringTransactionId,
    String? externalEntityId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addSplitTransaction, [], {
              #totalAmount: totalAmount,
              #type: type,
              #label: label,
              #date: date,
              #realAccount: realAccount,
              #splits: splits,
              #category: category,
              #note: note,
              #step: step,
              #status: status,
              #recurringTransactionId: recurringTransactionId,
              #externalEntityId: externalEntityId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addAdjustment({
    required double? adjustmentAmount,
    required String? label,
    required _i6.RealAccount? realAccount,
    required _i6.VirtualAccount? targetVirtualAccount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addAdjustment, [], {
              #adjustmentAmount: adjustmentAmount,
              #label: label,
              #realAccount: realAccount,
              #targetVirtualAccount: targetVirtualAccount,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTransaction(_i5.TransactionModel? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [transaction]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addTransfer({
    required double? amount,
    required String? label,
    required DateTime? date,
    required _i6.VirtualAccount? sourceVirtualAccount,
    required _i6.VirtualAccount? targetVirtualAccount,
    String? category,
    String? note,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addTransfer, [], {
              #amount: amount,
              #label: label,
              #date: date,
              #sourceVirtualAccount: sourceVirtualAccount,
              #targetVirtualAccount: targetVirtualAccount,
              #category: category,
              #note: note,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateTransaction({
    required _i5.TransactionModel? originalTransaction,
    required double? amount,
    required _i5.TransactionType? type,
    required String? label,
    required DateTime? date,
    required _i6.RealAccount? realAccount,
    required _i6.VirtualAccount? targetVirtualAccount,
    _i5.TransactionStep? step,
    String? category,
    String? note,
    String? externalEntityId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTransaction, [], {
              #originalTransaction: originalTransaction,
              #amount: amount,
              #type: type,
              #label: label,
              #date: date,
              #realAccount: realAccount,
              #targetVirtualAccount: targetVirtualAccount,
              #step: step,
              #category: category,
              #note: note,
              #externalEntityId: externalEntityId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateSplitTransaction({
    required _i5.TransactionModel? originalTransaction,
    required double? totalAmount,
    required _i5.TransactionType? type,
    required String? label,
    required DateTime? date,
    required _i6.RealAccount? realAccount,
    required List<({_i6.VirtualAccount account, double amount})>? splits,
    _i5.TransactionStep? step,
    String? category,
    String? note,
    String? externalEntityId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateSplitTransaction, [], {
              #originalTransaction: originalTransaction,
              #totalAmount: totalAmount,
              #type: type,
              #label: label,
              #date: date,
              #realAccount: realAccount,
              #splits: splits,
              #step: step,
              #category: category,
              #note: note,
              #externalEntityId: externalEntityId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> confirmTransaction(
    _i5.TransactionModel? originalTransaction,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#confirmTransaction, [originalTransaction]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> provisionTransaction(
    _i5.TransactionModel? originalTransaction,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#provisionTransaction, [originalTransaction]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cancelTransaction(
    _i5.TransactionModel? originalTransaction,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cancelTransaction, [originalTransaction]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
