// File generated by FlutterFire CLI / AI agent.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps in develop.
class DevFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2ucU5j1PmIoj3aitViNYyllgvSBTdwbc',
    appId: '1:549484887171:web:2c2b138e4f6388fdee6fb6',
    messagingSenderId: '549484887171',
    projectId: 'finance-manager-2026-dev',
    authDomain: 'finance-manager-2026-dev.firebaseapp.com',
    storageBucket: 'finance-manager-2026-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDia1u0K5DWSmzCrOznuBMPlg_V_e6uSFc',
    appId: '1:549484887171:android:79d75ab3e8fd67cbee6fb6',
    messagingSenderId: '549484887171',
    projectId: 'finance-manager-2026-dev',
    storageBucket: 'finance-manager-2026-dev.firebasestorage.app',
  );
}
